title: Masrizal Eka Yulianto,S.Kom.
logo: /assets/img/headshot_circle.png
description: Hire me on via email (masrizal04@gmail.com) or LinkedIn (https://www.linkedin.com/in/masrizaleka)
show_downloads: true
theme: jekyll-theme-minimal
